scrape_configs:
  - job_name: 'kubernetes_sd'
    scrape_interval: 5s
    scrape_timeout: 2s
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - sit
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: kubernetes_service
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod