apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: affiliate-prometheus
  namespace: sit
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  - pods
  verbs:
  - get
  - list
  - watch

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: affiliate-prometheus
  namespace: sit

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: affiliate-prometheus-role
  namespace: sit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: affiliate-prometheus
subjects:
- kind: ServiceAccount
  name: affiliate-prometheus
  namespace: sit