apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-service
  name: prometheus-service
  namespace: sit
spec:
  ports:
  - name: "9090"
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: prometheus-grafana
  type: LoadBalancer
